### ISSUE TITLE
CLI to generate yaml files

### ISSUE THREAD

**Issue by valeriano-manassero** [bodywork-ml/bodywork-core#107]
Hi,
there is the possibility to use the CLI to generate yaml files instead of interacting directly with K8s installation trough kubeconfig?

Since I usually apply GitOps pipelines to my MLops clusters I would like to test it putting deployments in a helm chart or kustomize yaml.

Afaik I didn't find any option to achieve this.

Ty.

**Comment by AlexIoannides** [comment]
If I understand you correctly, you're after the k8s manifests that get created from Bodywork deployments?

These don't get generated on the client side, as the Bodywork CLI interacts with k8s, only via k8s API calls (using the Python k8s client). So, the only way to get the manifests is from the cluster.

Bodywork's main aim in life is to remove the need for working with manifests, Helm charts, etc. We've thought a bit about [GitOps for ML](https://bodywork.readthedocs.io/en/latest/#cicd-for-machine-learning), which we've implement via [Bodywork cronjobs](https://bodywork.readthedocs.io/en/latest/user_guide/#scheduling-workflows). The thinking that guided this implementation, is that pipelines need to be re-run even if the Git repo's state hasn't changed - e.g. because data changes all the time, even if the training and serving codebase remains static. A Bodywork cronjob will always use the latest version of the Git repo, so it'll pick-up any changes that are made (I appreciate that this is not 'pure' GitOps).

This is an open debate and I'd appreciate your thoughts in this area. We can have a quick call if it's easier to discuss - ping me at alex [at[ bodyworkml.com.

**Comment by valeriano-manassero** [comment]
Hi @AlexIoannides ,
first ty for your detailed answer. Using corncobs makes sense since application management and data management are decoupled.

I missed `GitOps for ML` page; it's very interesting!

Usually I apply GitOps everywhere just to always have any state saved in Git so I know history and current state.
Moreover I don't like too much the cronjob approach for every use case, sometimes I prefer to have a web hook that triggers the sync. This is why I was asking for it here, I was thinking more to a `k8s operator` style approach.

I think we can share some thoughts if you like it; will drop you a mail or Linkedin message as soon as I will be free for some time. ty again!

**Comment by AlexIoannides** [comment]
Thank you - all feedback is greatly appreciated!

We have a REST API in development at the moment (hoping to release in Q3). This would allow you to trigger a pipeline via webhook. In the interim, you can still trigger workflows on an ad hoc basis using the [CLI](https://bodywork.readthedocs.io/en/latest/user_guide/#deploying-workflows) - e.g. via a CICD pipeline.
