### ISSUE TITLE
Is it intended to use print statements instead of logging?

### ISSUE THREAD

**Issue by jdvala** [bodywork-ml/bodywork-core#65]
First of all great project folks.

Secondly, its not a convention to use print statements, instead logging is used, I am just curious to know why you folks opted for print.

I can make a PR and introduce logging (using structlog) which will help this project to grow and make it easy for people to use API instead of using CLI.

Please let me know :)

**Comment by AlexIoannides** [comment]
Hi Jay.

Thanks for getting in touch.

I'm not sure that I fully understand your suggestion. Bodywork prints to stdout for the CLI, because that's most obvious way to write output for a CLI application (unless I am missing something). Everywhere else within the application, we use a custom logger derived from the `logging` module in the Python standard library - e.g., see [here](https://github.com/bodywork-ml/bodywork-core/blob/master/src/bodywork/logs.py).

**Comment by jdvala** [comment]
Sorry I checked only one file, but it makes a lot of sense to have print statements where we want STDOUT, I failed to check other files and assumed it is case everywhere. I am closing this issue.

**Comment by AlexIoannides** [comment]
There's no need to apologise Jay! Thanks for taking an interest and offering to help - it's appreciated 👍
